"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ZODIAC, ZODIAC_SIMPLIFIED } from "./constellations";
import DesignExplorer, { type SiteView } from "./design-explorer";
import StarExplorer from "./star-explorer";

type Phase = "idle" | "question" | "hint" | "countdown" | "play" | "reveal" | "score" | "quickQuestion" | "summary";
type Point = { id: string; x: number; y: number };
type Constellation = { id:string; th:string; en:string; symbol:string; points:Point[]; edges:[string,string][] };
type RoundResult = { id:string; th:string; en:string; score:number; max:number };
type EventId = "meteor"|"timewarp"|"blinking"|"blackhole"|"mirror"|"alien"|"decoy"|"introvert"|"quick"|"supernova";
type GameEvent = { id:EventId; title:string; icon:string; text:string; timing:"start"|"mid"|"after" };
const EVENTS:GameEvent[]=[
 {id:"meteor",title:"Meteor Shower",icon:"☄",text:"ฝนอุกกาบาตจะปิดพื้นที่ชั่วคราวระหว่างรอบ",timing:"mid"},
 {id:"timewarp",title:"Time Warp",icon:"◷",text:"เวลาเดินเร็วขึ้นเป็น 2 เท่า",timing:"start"},
 {id:"blinking",title:"Blinking Star",icon:"✦",text:"ดาวทั้งหมดกำลังกระพริบ",timing:"start"},
 {id:"blackhole",title:"Black Hole",icon:"●",text:"หลุมดำจะปิดพื้นที่หนึ่งชั่วคราว",timing:"mid"},
 {id:"mirror",title:"Mirror Mirror",icon:"◇",text:"กลุ่มดาวถูกสะท้อนกลับด้าน",timing:"start"},
 {id:"alien",title:"Alien Invasion",icon:"👾",text:"กำจัดเอเลี่ยนก่อนเลือกดาว",timing:"start"},
 {id:"decoy",title:"Decoy Chaos",icon:"✹",text:"ดาวหลอกเพิ่มขึ้นกว่าปกติ",timing:"start"},
 {id:"introvert",title:"Introvert Star",icon:"⊘",text:"มีดาวต้องห้าม ห้ามเหยียบเด็ดขาด",timing:"start"},
 {id:"quick",title:"Quick Question",icon:"?",text:"ตอบคำถามโบนัสหลังจบรอบ",timing:"after"},
 {id:"supernova",title:"Su Su Su Supernova",icon:"✺",text:"รอบนี้มีเวลา 20 วินาที ดาวบางดวงจะระเบิดหากไม่ Hover ภายใน 10 วินาที",timing:"start"},
];

function makeDecoys(target:Constellation,count:number){
 const xs=target.points.map(p=>p.x),ys=target.points.map(p=>p.y),minX=Math.max(6,Math.min(...xs)-13),maxX=Math.min(94,Math.max(...xs)+13),minY=Math.max(7,Math.min(...ys)-10),maxY=Math.min(71,Math.max(...ys)+10);
 const candidates=Array.from({length:240},(_,i)=>({id:`x${i+1}`,x:minX+Math.random()*(maxX-minX),y:minY+Math.random()*(maxY-minY)}));
 const picked:Point[]=[];
 for(const spacing of [6.2,5,4])for(const d of shuffle(candidates)){if(!picked.some(p=>p.id===d.id)&&target.points.every(p=>Math.hypot(p.x-d.x,p.y-d.y)>5.5)&&picked.every(p=>Math.hypot(p.x-d.x,p.y-d.y)>spacing))picked.push(d);if(picked.length===count)return picked}
 return picked.slice(0,count)
}
function shuffle<T>(items:T[]){const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function centeredPosition(p:Point){return {left:`calc(50% + ${p.x-50}%)`,top:`calc(50% + ${(p.y-39)/.78}%)`}}
function ConstellationMap({mode,current,nodes,targetIds,selected,phase,answer,assistLines,assistStars,onToggle,onHover,blackHolePoint,alienPoints,onAlienClick,supernovaIds}:{mode:"wall"|"floor";current:Constellation;nodes:Point[];targetIds:Set<string>;selected:Set<string>;phase:Phase;answer:boolean;assistLines:boolean;assistStars:boolean;onToggle:(id:string)=>void;onHover?:(id:string)=>void;blackHolePoint?:Point|null;alienPoints?:Point[];onAlienClick?:(id:string)=>void;supernovaIds?:Set<string>}){
 const interactive=mode==="floor",dense=nodes.length>20;
 return <div className={"constellation-stage "+(mode==="wall"?"wall-constellation":"floor-constellation")+(dense?" dense":"")} data-constellation-map={mode}>
  <svg className="connection-layer" viewBox="0 0 100 78" preserveAspectRatio="none" aria-hidden="true">{current.edges.map(([a,b],edgeIndex)=>{const p1=current.points.find(p=>p.id===a)!,p2=current.points.find(p=>p.id===b)!,discovered=selected.has(a)&&selected.has(b),hinted=assistLines&&!discovered&&!answer;return <line key={mode+"-"+edgeIndex+"-"+a+"-"+b} x1={p1.x} y1={p1.y} x2={p2.x} y2={p2.y} className={(answer||discovered)?"line visible":hinted?"line assist":"line"}/>})}</svg>
  <div className="nodes-layer">{nodes.map((p,i)=>{const active=selected.has(p.id),target=targetIds.has(p.id),correct=(phase==="reveal"||phase==="score")&&active&&target,wrong=(phase==="reveal"||phase==="score")&&active&&!target,missed=(phase==="reveal"||phase==="score")&&!active&&target,nodeClass="star-node "+(mode==="wall"?"wall-node ":"")+(active?"active ":"")+(correct?"correct ":"")+(wrong?"wrong ":"")+(missed?"missed ":"")+(answer&&target?"answer ":"")+(assistStars&&target&&!active?"assist-target ":"")+(supernovaIds?.has(p.id)&&phase==="play"?"supernova ":""),style={...centeredPosition(p),animationDelay:(i*.04)+"s"};return interactive?<button key={p.id} className={nodeClass} style={style} data-point-id={p.id} onClick={()=>{onHover?.(p.id);onToggle(p.id)}} onPointerEnter={()=>onHover?.(p.id)} disabled={phase!=="play"} aria-label={"ดาวตำแหน่ง "+(i+1)+(active?" ถูกเลือก":"")} aria-pressed={active}><span className="star-core">✦</span><span className="sensor-ring"/><span className="node-label">{active?"PLAYER":""}</span></button>:<span key={p.id} className={nodeClass} style={style} data-point-id={p.id} aria-hidden="true"><span className="star-core">✦</span><span className="sensor-ring"/><span className="node-label">{active?"PLAYER":""}</span></span>})}</div>
  {interactive&&blackHolePoint&&<div className="blackhole-zone" style={centeredPosition(blackHolePoint)} aria-label="พื้นที่หลุมดำ ห้ามเลือกดาวในวงนี้"><span>BLACK HOLE</span></div>}
  {interactive&&alienPoints&&alienPoints.length>0&&<div className="alien-swarm">{alienPoints.map((point,i)=><button key={point.id} style={{...centeredPosition(point),right:"auto",bottom:"auto",animationDelay:`${i*.12}s`}} onClick={()=>onAlienClick?.(point.id)} aria-label={`กำจัดเอเลี่ยนที่ดาว ${point.id}`}>👾</button>)}</div>}
 </div>
}

export default function Home(){
 const [siteView,setSiteView]=useState<SiteView>("game");
 const [learnMode,setLearnMode]=useState(false);
 const [phase,setPhase]=useState<Phase>("idle"),[rounds,setRounds]=useState<Constellation[]>([]),[roundIndex,setRoundIndex]=useState(0),[timeLeft,setTimeLeft]=useState(20),[countdown,setCountdown]=useState(3),[questionSeconds,setQuestionSeconds]=useState(5),[questionLeaving,setQuestionLeaving]=useState(false),[selected,setSelected]=useState<Set<string>>(new Set()),[results,setResults]=useState<RoundResult[]>([]),[fastMode,setFastMode]=useState(false),[simplified,setSimplified]=useState(true),[resetIn,setResetIn]=useState(12),[roundDecoys,setRoundDecoys]=useState<Point[]>([]),[attractIndex,setAttractIndex]=useState(4),[attractSeconds,setAttractSeconds]=useState(15),[attractFade,setAttractFade]=useState<""|"out"|"in">(""),[activeEvent,setActiveEvent]=useState<GameEvent|null>(null),[displayEvent,setDisplayEvent]=useState<GameEvent|null>(null),[eventHistory,setEventHistory]=useState<EventId[]>([]),[eventSeconds,setEventSeconds]=useState(0),[midEventBursts,setMidEventBursts]=useState(0),[blackHolePoint,setBlackHolePoint]=useState<Point|null>(null),[alienIds,setAlienIds]=useState<Set<string>>(new Set()),[quickSeconds,setQuickSeconds]=useState(10),[quickAnswered,setQuickAnswered]=useState(false),[supernovaIds,setSupernovaIds]=useState<Set<string>>(new Set()),[supernovaGone,setSupernovaGone]=useState<Set<string>>(new Set()),[eventRolling,setEventRolling]=useState(false);
 const catalog=simplified?ZODIAC_SIMPLIFIED:ZODIAC;
 const timerRef=useRef<ReturnType<typeof setInterval>|null>(null),supernovaHoveredRef=useRef<Set<string>>(new Set()),eventHistoryRef=useRef<EventId[]>([]),current=rounds[roundIndex]??catalog[2],attractCurrent=ZODIAC[attractIndex];
 const total=results.reduce((s,r)=>s+r.score,0),maxTotal=results.reduce((s,r)=>s+r.max,0),sessionMax=rounds.reduce((s,r)=>s+r.points.length,0);
 const nodes=useMemo(()=>[...current.points,...roundDecoys],[current,roundDecoys]);
 const alienPoints=useMemo(()=>nodes.filter(p=>alienIds.has(p.id)),[nodes,alienIds]);
 const aliensLeft=alienIds.size,alienCleared=aliensLeft===0;
 const targetIds=useMemo(()=>new Set(current.points.map(p=>p.id)),[current]);
 const availableTargetIds=useMemo(()=>new Set([...targetIds].filter(id=>!supernovaGone.has(id))),[targetIds,supernovaGone]);
 const penalized=useMemo(()=>new Set([...selected].filter(id=>!targetIds.has(id))),[selected,targetIds]);
 const attractIds=useMemo(()=>new Set(attractCurrent.points.map(p=>p.id)),[attractCurrent]);
 const clearTimer=()=>{if(timerRef.current){clearInterval(timerRef.current);timerRef.current=null}};
 const startHint=useCallback((index:number,target?:Constellation)=>{clearTimer();setRoundIndex(index);const map=target??rounds[index]??catalog[2],decoyCount=activeEvent?.id==="decoy"?16:9+Math.floor(Math.random()*4);const decoys=makeDecoys(map,decoyCount);setRoundDecoys(decoys);setSelected(new Set());setAlienIds(activeEvent?.id==="alien"?new Set(shuffle([...map.points,...decoys]).slice(0,10).map(p=>p.id)):new Set());setSupernovaGone(new Set());supernovaHoveredRef.current=new Set();setPhase("hint");window.setTimeout(()=>{setCountdown(3);setPhase("countdown")},2000)},[rounds,catalog,activeEvent]);
 const showQuestion=useCallback((index:number)=>{clearTimer();const previous=eventHistoryRef.current,pool=EVENTS.filter(event=>!previous.slice(-3).includes(event.id)),next=pool[Math.floor(Math.random()*pool.length)]??EVENTS[0],history=[...previous,next.id].slice(-5);eventHistoryRef.current=history;setRoundIndex(index);setEventHistory(history);setActiveEvent(next);setDisplayEvent(next);setEventRolling(true);window.setTimeout(()=>{setDisplayEvent(next);setEventRolling(false)},2200);setRoundDecoys([]);setSelected(new Set());setQuestionSeconds(5);setQuestionLeaving(false);setPhase("question")},[]);
 const startGame=()=>{const picked=shuffle(catalog).slice(0,5);eventHistoryRef.current=[];setEventHistory([]);setRounds(picked);setResults([]);setRoundIndex(0);setSelected(new Set());window.setTimeout(()=>showQuestion(0),0)};
 const evaluate=useCallback(()=>{clearTimer();const introvertId=current.points[0]?.id,introvert=activeEvent?.id==="introvert",forbidden=introvert&&selected.has(introvertId),autoCredit=introvert&&!forbidden&&availableTargetIds.has(introvertId)?1:0,correct=current.points.filter(p=>availableTargetIds.has(p.id)&&selected.has(p.id)).length,score=forbidden?0:Math.max(0,correct+autoCredit-penalized.size);const result={id:current.id,th:current.th,en:current.en,score,max:availableTargetIds.size};setResults(prev=>[...prev,result]);if(activeEvent?.id==="quick"){setQuickSeconds(10);setQuickAnswered(false);setPhase("quickQuestion")}else{setPhase("reveal");window.setTimeout(()=>setPhase("score"),3000);window.setTimeout(()=>roundIndex>=4?setPhase("summary"):showQuestion(roundIndex+1),5000)}},[current,selected,penalized,availableTargetIds,roundIndex,showQuestion,activeEvent]);
 useEffect(()=>{if(phase!=="question")return;setQuestionSeconds(5);setQuestionLeaving(false);const tick=window.setInterval(()=>setQuestionSeconds(v=>Math.max(1,v-1)),1000),leave=window.setTimeout(()=>setQuestionLeaving(true),4300),next=window.setTimeout(()=>startHint(roundIndex,rounds[roundIndex]),5000);return()=>{window.clearInterval(tick);window.clearTimeout(leave);window.clearTimeout(next)}},[phase,roundIndex,rounds,startHint]);
 useEffect(()=>{if(phase!=="countdown")return;const id=window.setInterval(()=>setCountdown(v=>{if(v<=1){window.clearInterval(id);setTimeLeft(activeEvent?.id==="supernova"?20:fastMode?10:20);setEventSeconds(0);setMidEventBursts(0);setBlackHolePoint(null);setSupernovaIds(activeEvent?.id==="supernova"?new Set(shuffle(current.points).slice(0,Math.max(2,Math.ceil(current.points.length/3))).map(point=>point.id)):new Set());setSupernovaGone(new Set());supernovaHoveredRef.current=new Set();setPhase("play");return 0}return v-1}),1000);return()=>window.clearInterval(id)},[phase,fastMode,activeEvent,current]);
 useEffect(()=>{if(phase!=="play")return;const isWarp=activeEvent?.id==="timewarp";timerRef.current=setInterval(()=>setTimeLeft(v=>{if(v<=1){clearTimer();window.setTimeout(evaluate,0);return 0}return v-1}),isWarp?500:1000);return clearTimer},[phase,evaluate,activeEvent]);
 useEffect(()=>{if(phase!=="play"||eventSeconds<=0)return;const id=window.setInterval(()=>setEventSeconds(v=>Math.max(0,v-1)),1000);return()=>window.clearInterval(id)},[phase,eventSeconds]);
 useEffect(()=>{if(phase!=="play"||!activeEvent||!(["meteor","blackhole"] as EventId[]).includes(activeEvent.id)||eventSeconds>0||midEventBursts>=2)return;const delay=fastMode?800+Math.random()*400:1800+Math.random()*2200;const id=window.setTimeout(()=>{if(activeEvent.id==="blackhole")setBlackHolePoint(shuffle([...current.points,...roundDecoys])[0]??null);setEventSeconds(3);setMidEventBursts(value=>value+1)},delay);return()=>window.clearTimeout(id)},[phase,activeEvent,eventSeconds,midEventBursts,fastMode,current,roundDecoys]);
 useEffect(()=>{if(phase!=="play"||activeEvent?.id!=="supernova"||supernovaIds.size===0)return;const id=window.setTimeout(()=>setSupernovaGone(new Set([...supernovaIds].filter(star=>!supernovaHoveredRef.current.has(star)))),10000);return()=>window.clearTimeout(id)},[phase,activeEvent,supernovaIds]);
 useEffect(()=>{if(phase!=="quickQuestion")return;const id=window.setInterval(()=>setQuickSeconds(v=>Math.max(0,v-1)),1000),done=window.setTimeout(()=>roundIndex>=4?setPhase("summary"):showQuestion(roundIndex+1),10000);return()=>{window.clearInterval(id);window.clearTimeout(done)}},[phase,roundIndex,showQuestion]);
 useEffect(()=>{if(phase!=="idle")return;setAttractIndex(Math.floor(Math.random()*ZODIAC.length));setAttractSeconds(15);let swap=0,finish=0;const ticker=window.setInterval(()=>setAttractSeconds(value=>{if(value>1)return value-1;setAttractFade("out");swap=window.setTimeout(()=>{setAttractIndex(previous=>{let next=previous;while(next===previous)next=Math.floor(Math.random()*ZODIAC.length);return next});setAttractFade("in");finish=window.setTimeout(()=>setAttractFade(""),700)},450);return 15}),1000);return()=>{window.clearInterval(ticker);window.clearTimeout(swap);window.clearTimeout(finish);setAttractFade("")}},[phase]);
 useEffect(()=>{if(phase!=="summary")return;setResetIn(12);const tick=window.setInterval(()=>setResetIn(v=>Math.max(0,v-1)),1000),reset=window.setTimeout(()=>{setPhase("idle");setRounds([]);setResults([]);setRoundIndex(0);setSelected(new Set())},12000);return()=>{window.clearInterval(tick);window.clearTimeout(reset)}},[phase]);
 const toggle=(id:string)=>{if(phase!=="play"||eventSeconds>0&&activeEvent?.id==="meteor"||supernovaGone.has(id))return;if(activeEvent?.id==="blackhole"&&eventSeconds>0&&blackHolePoint){const point=nodes.find(p=>p.id===id),map=document.querySelector('[data-constellation-map="floor"]')?.getBoundingClientRect();if(point&&map&&Math.hypot((point.x-blackHolePoint.x)*map.width/100,(point.y-blackHolePoint.y)*map.height/78)<75)return}if(activeEvent?.id==="alien"&&!alienCleared)return;setSelected(previous=>{const next=new Set(previous);if(next.has(id))next.delete(id);else next.add(id);return next})};
 const hoverSupernova=(id:string)=>{if(activeEvent?.id==="supernova"&&supernovaIds.has(id))supernovaHoveredRef.current.add(id)};
 const answer=phase==="hint"||phase==="reveal"||phase==="score";
 const assistLines=false,assistStars=false,correctSelected=current.points.filter(p=>availableTargetIds.has(p.id)&&selected.has(p.id)).length,evaluatedRoundScore=results.at(-1)?.score??0,completion=availableTargetIds.size?Math.round(correctSelected/availableTargetIds.size*100):0;
 const status=phase==="idle"?"ATTRACT MODE · พร้อมเริ่มภารกิจ":phase==="question"?"อีเวนต์ประจำรอบ":phase==="hint"?"จดจำรูปกลุ่มดาว":phase==="countdown"?"เตรียมเข้าประจำตำแหน่ง":phase==="play"?"เลือกดาวที่ถูกต้อง":phase==="reveal"?"เฉลยคำตอบ":phase==="score"?"คะแนนรอบนี้":phase==="quickQuestion"?"คำถามโบนัส":"สรุปภารกิจ";
 const shownEvent=displayEvent??activeEvent;
 if(learnMode) return <StarExplorer onStart={()=>{setLearnMode(false);startGame()}} onExit={()=>setLearnMode(false)}/>;
 if(siteView!=="game") return <DesignExplorer view={siteView} onView={setSiteView}/>;
 return <main className="app-shell"><div className="ambient ambient-a"/><div className="ambient ambient-b"/>
  <header className="topbar"><div className="brand"><span className="brand-mark">✦</span><span>CONSTELLATION MAKER</span></div><nav className="site-view-nav" aria-label="ดูเกมและเอกสารออกแบบ"><button className="active" onClick={()=>setSiteView("game")}>เล่นเกม</button><button className="learn-nav-button" onClick={()=>setLearnMode(true)} disabled={phase!=="idle"}>Learn Mode</button><button onClick={()=>setSiteView("mockup")}>UI Mockup</button><button onClick={()=>setSiteView("flow")}>Game Flow</button></nav><div className="mode-controls"><label className="fast-toggle map-toggle"><input type="checkbox" checked={simplified} onChange={e=>setSimplified(e.target.checked)} disabled={phase!=="idle"}/><span/><b>{simplified?"SIMPLIFIED":"REAL"}</b><small>{phase==="idle"?"NEXT GAME":`${current.points.length} PTS`}</small></label><label className="fast-toggle"><input type="checkbox" checked={fastMode} onChange={e=>setFastMode(e.target.checked)} disabled={phase!=="idle"&&phase!=="summary"}/><span/>โหมดทดสอบ 10 วิ</label></div></header>
  <section className={`wall-screen phase-${phase}${activeEvent&&activeEvent.id!=="mirror"?` event-${activeEvent.id}`:""}${phase==="idle"&&attractFade?` attract-fade-${attractFade}`:""}${phase==="question"&&questionLeaving?" question-leaving":""}`} aria-label="จอโค้งบนกำแพงสำหรับแสดงข้อมูล"><div className="screen-grid"/><div className="round-pill">{phase==="idle"?`NEXT CONSTELLATION · ${String(attractSeconds).padStart(2,"0")} SEC`:`ROUND ${Math.min(roundIndex+1,5)} / 5`}</div><div className="wall-center"><div className="zodiac-symbol">{phase==="idle"?attractCurrent.symbol:current.symbol}</div><div><p className="eyebrow">{status}</p><h1>{phase==="idle"?"ปลุกกลุ่มดาวให้สว่างไปด้วยกัน":current.th}</h1><p className="english-name">{phase==="idle"?"STEP ON A STAR · BUILD THE CONSTELLATION":current.en}</p></div></div>
  {phase==="idle"&&<ConstellationMap key={`wall-${attractCurrent.id}`} mode="wall" current={attractCurrent} nodes={attractCurrent.points} targetIds={attractIds} selected={attractIds} phase="idle" answer={false} assistLines={false} assistStars={false} onToggle={()=>{}}/>}
  {phase==="question"&&<ConstellationMap mode="wall" current={current} nodes={current.points} targetIds={targetIds} selected={targetIds} phase="question" answer={false} assistLines={false} assistStars={false} onToggle={()=>{}}/>}
  {phase!=="idle"&&phase!=="question"&&phase!=="summary"&&<ConstellationMap mode="wall" current={current} nodes={nodes.filter(p=>!supernovaGone.has(p.id))} targetIds={availableTargetIds} selected={selected} phase={phase} answer={answer} assistLines={assistLines} assistStars={assistStars} onToggle={toggle} onHover={hoverSupernova}/>}
  {phase==="question"&&<div className={`question-overlay ${eventRolling?"event-rolling":""}`}><small>ROUND {roundIndex+1} / 5 · RANDOM EVENT</small><div className="event-slot"><span>{shownEvent?.icon}</span><strong>{shownEvent?.title}</strong></div><p>อีเวนต์ประจำรอบ</p><b>{activeEvent?.text}</b><div className="player-requirement"><strong>{current.points.length}</strong><span>{current.th}<small>{activeEvent?.timing==="start"?"เริ่มพร้อมรอบนี้":activeEvent?.timing==="mid"?"เกิดระหว่างเล่น":"คำถามหลังจบรอบ"}</small></span></div><div className="question-progress"><i/></div></div>}
  {phase==="quickQuestion"&&<div className="quick-question-top"><small>QUICK QUESTION · {quickSeconds}s</small><div className="quick-question-figure"><svg viewBox="0 0 100 78" aria-label={`รูปกลุ่มดาว${current.th}`}><g>{current.edges.map(([a,b],i)=>{const p1=current.points.find(p=>p.id===a),p2=current.points.find(p=>p.id===b);return p1&&p2?<line key={i} x1={p1.x} y1={p1.y} x2={p2.x} y2={p2.y}/>:null})}</g>{current.points.map(p=><circle key={p.id} cx={p.x} cy={p.y} r="2.4"/>)}</svg></div><h2>ภาพนี้คือกลุ่มดาวราศีใด?</h2><p>{quickAnswered?"ตอบแล้ว!":"เลือกคำตอบที่จอล่าง"}</p></div>}
  <div className={`timer ${timeLeft<=10&&phase==="play"?"urgent":""}`}><span>{phase==="play"?String(timeLeft).padStart(2,"0"):phase==="question"?String(questionSeconds).padStart(2,"0"):phase==="idle"?"∞":"—"}</span><small>{phase==="play"?"SECONDS":phase==="question"?"INTRO":phase==="idle"?"WAITING":"TIMER"}</small></div>{phase==="countdown"&&<div className="countdown-overlay wall-countdown"><small>GET READY</small><strong key={countdown}>{countdown}</strong></div>}<div className="score-chip">{phase==="idle"?<><small>CONSTELLATION</small><strong>{attractCurrent.en}</strong><span>/ {attractCurrent.points.length} STARS</span></>:<><small>SCORE</small><strong>{phase==="play"?total+correctSelected:total}</strong><span>/{sessionMax||"—"}</span></>}</div>
  {phase==="idle"&&<div className="wall-cta"><p><b>{attractCurrent.symbol} {attractCurrent.en}</b><span>{attractCurrent.th} · เปลี่ยนรูปใหม่ใน {attractSeconds} วินาที</span></p><button onClick={startGame}><i/>ยืนบนดาวหรือกดเพื่อเริ่มภารกิจ <span>→</span></button></div>}
  {phase==="score"&&<div className="result-pop"><small>ROUND SCORE</small><strong>{results.at(-1)?.score}/{results.at(-1)?.max}</strong><span>{results.at(-1)?.score===results.at(-1)?.max?"PERFECT CONSTELLATION!":"เกือบสำเร็จ ลองจดจำรูปต่อไป"}</span></div>}
  {phase==="summary"&&<div className="summary-overlay"><p className="eyebrow">MISSION COMPLETE</p><h2>{total}/{maxTotal} คะแนน</h2><div className="rank">ความแม่นยำ {maxTotal?Math.round(total/maxTotal*100):0}%</div><div className="round-results">{results.map((r,i)=><div key={r.id}><span>{i+1}</span><p>{r.th}<small>{r.en}</small></p><strong>{r.score}/{r.max}</strong></div>)}</div><div className="auto-reset">กลับหน้าหลักอัตโนมัติใน {resetIn} วินาที</div></div>}</section>
  <div className="display-divider"><span>WALL DISPLAY</span><i/><span>INTERACTIVE FLOOR</span></div>
  <section className={`floor-zone phase-${phase}${activeEvent?` event-${activeEvent.id}`:""}${phase==="idle"&&attractFade?` attract-fade-${attractFade}`:""}${phase==="question"&&questionLeaving?" question-leaving":""}`} aria-label="จอพื้นที่โต้ตอบได้"><div className="floor-arc"><div className="floor-grid"/></div><div className="floor-instruction"><span className="live-dot"/>{phase==="play"?(eventSeconds>0?`${activeEvent?.title} ทำงานอยู่ · รออีก ${eventSeconds} วินาที`:activeEvent?.id==="alien"&&!alienCleared?`กำจัดเอเลี่ยนอีก ${aliensLeft} ตัวก่อนเลือกดาว`:activeEvent?.id==="timewarp"?"TIME WARP · เวลาเดินเร็ว 2 เท่า":"คลิกหรือแตะดาวเพื่อเลือก · กดซ้ำเพื่อเอาออก · ดาวหลอกที่ยังเลือกอยู่จะหัก 1 แต้มเมื่อจบรอบ"):phase==="question"?"":phase==="hint"?"คำใบ้จะแสดง 2 วินาที":phase==="countdown"?"เตรียมเข้าประจำตำแหน่ง":phase==="reveal"||phase==="score"?"สีเขียว = ถูก · สีแดง = ดาวหลอก · วงแหวน = จุดที่พลาด":phase==="idle"?`${attractCurrent.th}กำลังรอคุณ · เปลี่ยนรูปใหม่ใน ${attractSeconds} วินาที`:phase==="quickQuestion"?"ตอบคำถามโบนัสภายใน 10 วินาที":"จอพื้นจำลอง · จำนวนผู้เล่นยืดหยุ่นตามจำนวนจุดจริง"}</div>{phase==="countdown"&&<div className="countdown-overlay floor-countdown"><small>เตรียมตัว</small><strong key={`floor-${countdown}`}>{countdown}</strong></div>}
  {phase==="play"&&activeEvent?.id==="meteor"&&eventSeconds>0&&<div className="meteor-overlay">☄　☄　☄　☄</div>}
  {phase==="quickQuestion"&&<div className="quick-options quick-options-floor"><button onClick={()=>{setQuickAnswered(true);setQuickSeconds(0)}}>{current.symbol} {current.th}</button><button onClick={()=>{setQuickAnswered(true);setQuickSeconds(0)}}>✦ กลุ่มดาวอื่น</button></div>}
  {phase==="play"&&<div className="completion-chip">COMPLETION <strong>{completion}%</strong><small>{correctSelected}/{availableTargetIds.size} TARGETS</small></div>}{(phase==="reveal"||phase==="score")&&penalized.size>0&&<div className="penalty-chip">−{penalized.size} <small>ดาวหลอก</small></div>}<ConstellationMap key={phase==="idle"?`floor-${attractCurrent.id}`:phase==="question"?`floor-question-${current.id}`:"floor-game"} mode="floor" current={phase==="idle"?attractCurrent:current} nodes={phase==="idle"?attractCurrent.points:phase==="question"?current.points:nodes.filter(p=>!supernovaGone.has(p.id))} targetIds={phase==="idle"?attractIds:phase==="question"?targetIds:availableTargetIds} selected={phase==="idle"?attractIds:phase==="question"?targetIds:selected} phase={phase} answer={answer} assistLines={assistLines} assistStars={assistStars} onToggle={toggle} onHover={hoverSupernova} blackHolePoint={phase==="play"&&activeEvent?.id==="blackhole"&&eventSeconds>0?blackHolePoint:null} alienPoints={phase==="play"&&activeEvent?.id==="alien"&&!alienCleared?alienPoints:[]} onAlienClick={(id)=>setAlienIds(previous=>{const next=new Set(previous);next.delete(id);return next})} supernovaIds={supernovaIds}/>
  <div className="floor-legend"><span><i className="legend-star"/> ดาวที่เลือก</span><span><i className="legend-line"/> เส้นเชื่อมที่ค้นพบ</span><span><kbd>CLICK</kbd> จำลองการเหยียบ</span></div></section>
  <footer className="control-dock"><div><span className="control-label">GAME STATE</span><strong>{phase==="idle"?"ATTRACT":phase.toUpperCase()}</strong></div><div><span className="control-label">{phase==="idle"?"PREVIEW STARS":"ROUND SCORE"}</span><strong>{phase==="idle"?attractCurrent.points.length:phase==="play"?correctSelected:(phase==="reveal"||phase==="score")?evaluatedRoundScore:0}<small>{phase==="idle"?`/ ${attractCurrent.points.length}`:(phase==="reveal"||phase==="score")?` · −${penalized.size} PENALTY`:" · PENDING"}</small></strong></div><div className="progress-block"><span className="control-label">ROUND PROGRESS</span><div className="progress-dots">{[0,1,2,3,4].map(i=><i key={i} className={i<results.length?"done":i===roundIndex&&phase!=="idle"?"current":""}/>)}</div></div>{phase==="play"&&<button className="submit-button" onClick={evaluate}>SUBMIT คำตอบ <span>✓</span></button>}{phase!=="idle"&&phase!=="summary"&&<button className="reset-button" onClick={()=>{clearTimer();setPhase("idle");setResults([]);setSelected(new Set())}}>ยกเลิกเกม</button>}</footer>
 </main>
}
