"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";

type Phase = "idle" | "hint" | "countdown" | "play" | "reveal" | "score" | "summary";
type Point = { id: string; x: number; y: number };
type Constellation = { id:string; th:string; en:string; symbol:string; points:Point[]; edges:[string,string][] };
type RoundResult = { id:string; th:string; en:string; score:number; max:number };

const ZODIAC:Constellation[]=[
{id:"aries",th:"ราศีเมษ",en:"ARIES",symbol:"♈",points:[{id:"a",x:27,y:61},{id:"b",x:40,y:45},{id:"c",x:55,y:42},{id:"d",x:67,y:51}],edges:[["a","b"],["b","c"],["c","d"]]},
{id:"taurus",th:"ราศีพฤษภ",en:"TAURUS",symbol:"♉",points:[{id:"a",x:27,y:32},{id:"b",x:42,y:49},{id:"c",x:56,y:58},{id:"d",x:70,y:48},{id:"e",x:82,y:31}],edges:[["a","b"],["b","c"],["c","d"],["d","e"]]},
{id:"gemini",th:"ราศีเมถุน",en:"GEMINI",symbol:"♊",points:[{id:"a",x:34,y:30},{id:"b",x:62,y:30},{id:"c",x:36,y:55},{id:"d",x:60,y:55},{id:"e",x:49,y:45}],edges:[["a","c"],["b","d"],["a","b"],["c","e"],["e","d"]]},
{id:"cancer",th:"ราศีกรกฎ",en:"CANCER",symbol:"♋",points:[{id:"a",x:30,y:56},{id:"b",x:42,y:43},{id:"c",x:57,y:47},{id:"d",x:70,y:35}],edges:[["a","b"],["b","c"],["c","d"]]},
{id:"leo",th:"ราศีสิงห์",en:"LEO",symbol:"♌",points:[{id:"a",x:25,y:56},{id:"b",x:39,y:46},{id:"c",x:54,y:49},{id:"d",x:65,y:35},{id:"e",x:76,y:48}],edges:[["a","b"],["b","c"],["c","d"],["d","e"],["e","c"]]},
{id:"virgo",th:"ราศีกันย์",en:"VIRGO",symbol:"♍",points:[{id:"a",x:25,y:38},{id:"b",x:41,y:52},{id:"c",x:55,y:43},{id:"d",x:69,y:57},{id:"e",x:80,y:40}],edges:[["a","b"],["b","c"],["c","d"],["d","e"]]},
{id:"libra",th:"ราศีตุล",en:"LIBRA",symbol:"♎",points:[{id:"a",x:30,y:55},{id:"b",x:42,y:38},{id:"c",x:58,y:38},{id:"d",x:70,y:55}],edges:[["a","b"],["b","c"],["c","d"],["d","a"]]},
{id:"scorpius",th:"ราศีพิจิก",en:"SCORPIUS",symbol:"♏",points:[{id:"a",x:24,y:36},{id:"b",x:37,y:46},{id:"c",x:50,y:54},{id:"d",x:65,y:52},{id:"e",x:77,y:35}],edges:[["a","b"],["b","c"],["c","d"],["d","e"]]},
{id:"sagittarius",th:"ราศีธนู",en:"SAGITTARIUS",symbol:"♐",points:[{id:"a",x:29,y:58},{id:"b",x:43,y:45},{id:"c",x:57,y:55},{id:"d",x:67,y:38},{id:"e",x:79,y:27}],edges:[["a","b"],["b","c"],["c","d"],["d","e"],["b","d"]]},
{id:"capricornus",th:"ราศีมกร",en:"CAPRICORNUS",symbol:"♑",points:[{id:"a",x:25,y:42},{id:"b",x:43,y:58},{id:"c",x:61,y:55},{id:"d",x:77,y:35}],edges:[["a","b"],["b","c"],["c","d"],["d","a"]]},
{id:"aquarius",th:"ราศีกุมภ์",en:"AQUARIUS",symbol:"♒",points:[{id:"a",x:25,y:43},{id:"b",x:39,y:33},{id:"c",x:51,y:48},{id:"d",x:64,y:38},{id:"e",x:78,y:51}],edges:[["a","b"],["b","c"],["c","d"],["d","e"]]},
{id:"pisces",th:"ราศีมีน",en:"PISCES",symbol:"♓",points:[{id:"a",x:24,y:39},{id:"b",x:37,y:51},{id:"c",x:50,y:45},{id:"d",x:65,y:54},{id:"e",x:78,y:38}],edges:[["a","b"],["b","c"],["c","d"],["d","e"]]}
];
const DECOYS:Point[]=[{id:"x1",x:16,y:67},{id:"x2",x:28,y:25},{id:"x3",x:42,y:69},{id:"x4",x:55,y:24},{id:"x5",x:68,y:68},{id:"x6",x:82,y:48},{id:"x7",x:20,y:42},{id:"x8",x:74,y:27}];
function shuffle<T>(items:T[]){const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function centeredPosition(p:Point){return {left:`calc(50% + ${p.x-50}%)`,top:`calc(50% + ${(p.y-39)/.78}%)`}}

export default function Home(){
 const [phase,setPhase]=useState<Phase>("idle"),[rounds,setRounds]=useState<Constellation[]>([]),[roundIndex,setRoundIndex]=useState(0),[timeLeft,setTimeLeft]=useState(40),[countdown,setCountdown]=useState(3),[selected,setSelected]=useState<Set<string>>(new Set()),[results,setResults]=useState<RoundResult[]>([]),[fastMode,setFastMode]=useState(false),[resetIn,setResetIn]=useState(12);
 const timerRef=useRef<ReturnType<typeof setInterval>|null>(null),current=rounds[roundIndex]??ZODIAC[2];
 const total=results.reduce((s,r)=>s+r.score,0),maxTotal=results.reduce((s,r)=>s+r.max,0),sessionMax=rounds.reduce((s,r)=>s+r.points.length,0);
 const nodes=useMemo(()=>shuffle([...current.points,...shuffle(DECOYS).slice(0,4)]),[current]);
 const targetIds=useMemo(()=>new Set(current.points.map(p=>p.id)),[current]);
 const clearTimer=()=>{if(timerRef.current){clearInterval(timerRef.current);timerRef.current=null}};
 const startHint=useCallback((index:number)=>{clearTimer();setRoundIndex(index);setSelected(new Set());setPhase("hint");window.setTimeout(()=>{setCountdown(3);setPhase("countdown")},2000)},[]);
 const startGame=()=>{const picked=shuffle(ZODIAC).slice(0,5);setRounds(picked);setResults([]);setRoundIndex(0);setSelected(new Set());window.setTimeout(()=>startHint(0),0)};
 const evaluate=useCallback(()=>{clearTimer();const score=current.points.filter(p=>selected.has(p.id)).length;const result={id:current.id,th:current.th,en:current.en,score,max:current.points.length};setResults(prev=>[...prev,result]);setPhase("reveal");window.setTimeout(()=>setPhase("score"),3000);window.setTimeout(()=>roundIndex>=4?setPhase("summary"):startHint(roundIndex+1),5000)},[current,selected,roundIndex,startHint]);
 useEffect(()=>{if(phase!=="countdown")return;const id=window.setInterval(()=>setCountdown(v=>{if(v<=1){window.clearInterval(id);setTimeLeft(fastMode?10:40);setPhase("play");return 0}return v-1}),1000);return()=>window.clearInterval(id)},[phase,fastMode]);
 useEffect(()=>{if(phase!=="play")return;timerRef.current=setInterval(()=>setTimeLeft(v=>{if(v<=1){clearTimer();window.setTimeout(evaluate,0);return 0}return v-1}),1000);return clearTimer},[phase,evaluate]);
 useEffect(()=>{if(phase!=="summary")return;setResetIn(12);const tick=window.setInterval(()=>setResetIn(v=>Math.max(0,v-1)),1000),reset=window.setTimeout(()=>{setPhase("idle");setRounds([]);setResults([]);setRoundIndex(0);setSelected(new Set())},12000);return()=>{window.clearInterval(tick);window.clearTimeout(reset)}},[phase]);
 const toggle=(id:string)=>{if(phase!=="play")return;setSelected(prev=>{const n=new Set(prev);if(n.has(id))n.delete(id);else if(n.size<5)n.add(id);return n})};
 const answer=phase==="hint"||phase==="reveal"||phase==="score";
 const status=phase==="idle"?"พร้อมเริ่มภารกิจ":phase==="hint"?"จดจำรูปกลุ่มดาว":phase==="countdown"?"เตรียมเข้าประจำตำแหน่ง":phase==="play"?"เลือกดาวที่ถูกต้อง":phase==="reveal"?"เฉลยคำตอบ":phase==="score"?"คะแนนรอบนี้":"สรุปภารกิจ";
 return <main className="app-shell"><div className="ambient ambient-a"/><div className="ambient ambient-b"/>
  <header className="topbar"><div className="brand"><span className="brand-mark">✦</span><span>CONSTELLATION MAKER</span></div><div className="prototype-label">WEB PROTOTYPE · INPUT SIMULATION</div><label className="fast-toggle"><input type="checkbox" checked={fastMode} onChange={e=>setFastMode(e.target.checked)} disabled={phase!=="idle"&&phase!=="summary"}/><span/>โหมดทดสอบ 10 วิ</label></header>
  <section className={`wall-screen phase-${phase}`} aria-label="จอโค้งบนกำแพงสำหรับแสดงข้อมูล"><div className="screen-grid"/><div className="round-pill">ROUND {Math.min(roundIndex+1,5)} / 5</div><div className="wall-center"><div className="zodiac-symbol">{phase==="idle"?"✦":current.symbol}</div><div><p className="eyebrow">{status}</p><h1>{phase==="idle"?"นักสร้างกลุ่มดาว":current.th}</h1><p className="english-name">{phase==="idle"?"CONSTELLATION MAKER":current.en}</p></div></div>
  {phase!=="idle"&&phase!=="summary"&&<div className="constellation-stage wall-constellation" aria-label="ภาพสะท้อนดาวที่ผู้เล่นเลือกบนจอพื้น"><svg viewBox="0 0 100 78" preserveAspectRatio="none" aria-hidden="true">{current.edges.map(([a,b])=>{const p1=current.points.find(p=>p.id===a)!,p2=current.points.find(p=>p.id===b)!,visible=answer||(selected.has(a)&&selected.has(b));return <line key={`wall-${a}-${b}`} x1={p1.x} y1={p1.y} x2={p2.x} y2={p2.y} className={visible?"wall-line visible":"wall-line"}/>})}</svg>{nodes.map((p,i)=>{const active=selected.has(p.id),target=targetIds.has(p.id),correct=(phase==="reveal"||phase==="score")&&active&&target,wrong=(phase==="reveal"||phase==="score")&&active&&!target,missed=(phase==="reveal"||phase==="score")&&!active&&target;return <span key={`wall-${p.id}`} className={`wall-star ${active?"active":""} ${correct?"correct":""} ${wrong?"wrong":""} ${missed?"missed":""} ${answer&&target?"answer":""}`} style={{...centeredPosition(p),animationDelay:`${i*.08}s`}}>✦</span>})}</div>}
  <div className={`timer ${timeLeft<=10&&phase==="play"?"urgent":""}`}><span>{phase==="play"?String(timeLeft).padStart(2,"0"):"—"}</span><small>{phase==="play"?"SECONDS":"TIMER"}</small></div>{phase==="countdown"&&<div className="countdown-overlay wall-countdown"><small>GET READY</small><strong key={countdown}>{countdown}</strong></div>}<div className="score-chip"><small>SCORE</small><strong>{total}</strong><span>/{sessionMax||"—"}</span></div>
  {phase==="idle"&&<div className="wall-cta"><p>จำรูป · เลือกดาว · สร้างกลุ่มดาวร่วมกัน</p><button onClick={startGame}>เริ่มภารกิจ <span>→</span></button></div>}
  {phase==="score"&&<div className="result-pop"><small>ROUND SCORE</small><strong>{results.at(-1)?.score}/{results.at(-1)?.max}</strong><span>{results.at(-1)?.score===results.at(-1)?.max?"PERFECT CONSTELLATION!":"เกือบสำเร็จ ลองจดจำรูปต่อไป"}</span></div>}
  {phase==="summary"&&<div className="summary-overlay"><p className="eyebrow">MISSION COMPLETE</p><h2>{total}/{maxTotal} คะแนน</h2><div className="rank">ความแม่นยำ {maxTotal?Math.round(total/maxTotal*100):0}%</div><div className="round-results">{results.map((r,i)=><div key={r.id}><span>{i+1}</span><p>{r.th}<small>{r.en}</small></p><strong>{r.score}/{r.max}</strong></div>)}</div><div className="auto-reset">กลับหน้าหลักอัตโนมัติใน {resetIn} วินาที</div></div>}</section>
  <div className="display-divider"><span>WALL DISPLAY</span><i/><span>INTERACTIVE FLOOR</span></div>
  <section className={`floor-zone phase-${phase}`} aria-label="จอพื้นที่โต้ตอบได้"><div className="floor-arc"><div className="floor-grid"/></div><div className="floor-instruction"><span className="live-dot"/>{phase==="play"?"คลิกหรือแตะดาวเพื่อจำลองผู้เล่นยืนบนตำแหน่ง":phase==="hint"?"คำใบ้จะแสดง 2 วินาที":phase==="countdown"?"เตรียมเข้าประจำตำแหน่ง":phase==="reveal"||phase==="score"?"สีเขียว = ถูก · สีแดง = ดาวหลอก · วงแหวน = จุดที่พลาด":"จอพื้นจำลองสำหรับผู้เล่นสูงสุด 5 คน"}</div>{phase==="countdown"&&<div className="countdown-overlay floor-countdown"><small>เตรียมตัว</small><strong key={`floor-${countdown}`}>{countdown}</strong></div>}
  <div className="constellation-stage floor-constellation"><svg className="connection-layer" viewBox="0 0 100 78" preserveAspectRatio="none" aria-hidden="true">{current.edges.map(([a,b])=>{const p1=current.points.find(p=>p.id===a)!,p2=current.points.find(p=>p.id===b)!,visible=answer||(selected.has(a)&&selected.has(b));return <line key={`${a}-${b}`} x1={p1.x} y1={p1.y} x2={p2.x} y2={p2.y} className={visible?"line visible":"line"}/>})}</svg>
  <div className="nodes-layer">{nodes.map((p,i)=>{const active=selected.has(p.id),target=targetIds.has(p.id),correct=(phase==="reveal"||phase==="score")&&active&&target,wrong=(phase==="reveal"||phase==="score")&&active&&!target,missed=(phase==="reveal"||phase==="score")&&!active&&target;return <button key={p.id} className={`star-node ${active?"active":""} ${correct?"correct":""} ${wrong?"wrong":""} ${missed?"missed":""} ${answer&&target?"answer":""}`} style={{...centeredPosition(p),animationDelay:`${i*.11}s`}} onClick={()=>toggle(p.id)} disabled={phase!=="play"} aria-label={`ดาวตำแหน่ง ${i+1}${active?" ถูกเลือก":""}`} aria-pressed={active}><span className="star-core">✦</span><span className="sensor-ring"/><span className="node-label">{active?"PLAYER":""}</span></button>})}</div></div>
  <div className="floor-legend"><span><i className="legend-star"/> ดาวที่เลือก</span><span><i className="legend-line"/> เส้นเชื่อมที่ค้นพบ</span><span><kbd>CLICK</kbd> จำลองการเหยียบ</span></div></section>
  <footer className="control-dock"><div><span className="control-label">GAME STATE</span><strong>{phase.toUpperCase()}</strong></div><div><span className="control-label">ACTIVE PLAYERS</span><strong>{selected.size}<small>/ 5</small></strong></div><div className="progress-block"><span className="control-label">ROUND PROGRESS</span><div className="progress-dots">{[0,1,2,3,4].map(i=><i key={i} className={i<results.length?"done":i===roundIndex&&phase!=="idle"?"current":""}/>)}</div></div>{phase==="play"&&<button className="submit-button" onClick={evaluate}>SUBMIT คำตอบ <span>✓</span></button>}{phase!=="idle"&&phase!=="summary"&&<button className="reset-button" onClick={()=>{clearTimer();setPhase("idle");setResults([]);setSelected(new Set())}}>ยกเลิกเกม</button>}</footer>
 </main>
}
