"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ZODIAC, ZODIAC_SIMPLIFIED } from "./constellations";
import DesignExplorer, { type SiteView } from "./design-explorer";

type Phase = "idle" | "question" | "hint" | "countdown" | "play" | "reveal" | "score" | "summary";
type Point = { id: string; x: number; y: number };
type Constellation = { id:string; th:string; en:string; symbol:string; points:Point[]; edges:[string,string][] };
type RoundResult = { id:string; th:string; en:string; score:number; max:number };

function makeDecoys(target:Constellation,count:number){
 const xs=target.points.map(p=>p.x),ys=target.points.map(p=>p.y),minX=Math.max(6,Math.min(...xs)-13),maxX=Math.min(94,Math.max(...xs)+13),minY=Math.max(7,Math.min(...ys)-10),maxY=Math.min(71,Math.max(...ys)+10);
 const candidates=Array.from({length:240},(_,i)=>({id:`x${i+1}`,x:minX+Math.random()*(maxX-minX),y:minY+Math.random()*(maxY-minY)}));
 const picked:Point[]=[];
 for(const spacing of [6.2,5,4])for(const d of shuffle(candidates)){if(!picked.some(p=>p.id===d.id)&&target.points.every(p=>Math.hypot(p.x-d.x,p.y-d.y)>5.5)&&picked.every(p=>Math.hypot(p.x-d.x,p.y-d.y)>spacing))picked.push(d);if(picked.length===count)return picked}
 return picked.slice(0,count)
}
function shuffle<T>(items:T[]){const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function centeredPosition(p:Point){return {left:`calc(50% + ${p.x-50}%)`,top:`calc(50% + ${(p.y-39)/.78}%)`}}
function ConstellationMap({mode,current,nodes,targetIds,selected,phase,answer,assistLines,assistStars,onToggle}:{mode:"wall"|"floor";current:Constellation;nodes:Point[];targetIds:Set<string>;selected:Set<string>;phase:Phase;answer:boolean;assistLines:boolean;assistStars:boolean;onToggle:(id:string)=>void}){
 const interactive=mode==="floor",dense=nodes.length>20;
 return <div className={"constellation-stage "+(mode==="wall"?"wall-constellation":"floor-constellation")+(dense?" dense":"")} data-constellation-map={mode}>
  <svg className="connection-layer" viewBox="0 0 100 78" preserveAspectRatio="none" aria-hidden="true">{current.edges.map(([a,b],edgeIndex)=>{const p1=current.points.find(p=>p.id===a)!,p2=current.points.find(p=>p.id===b)!,discovered=selected.has(a)&&selected.has(b),hinted=assistLines&&!discovered&&!answer;return <line key={mode+"-"+edgeIndex+"-"+a+"-"+b} x1={p1.x} y1={p1.y} x2={p2.x} y2={p2.y} className={(answer||discovered)?"line visible":hinted?"line assist":"line"}/>})}</svg>
  <div className="nodes-layer">{nodes.map((p,i)=>{const active=selected.has(p.id),target=targetIds.has(p.id),correct=(phase==="reveal"||phase==="score")&&active&&target,wrong=(phase==="reveal"||phase==="score")&&active&&!target,missed=(phase==="reveal"||phase==="score")&&!active&&target,nodeClass="star-node "+(mode==="wall"?"wall-node ":"")+(active?"active ":"")+(correct?"correct ":"")+(wrong?"wrong ":"")+(missed?"missed ":"")+(answer&&target?"answer ":"")+(assistStars&&target&&!active?"assist-target":""),style={...centeredPosition(p),animationDelay:(i*.04)+"s"};return interactive?<button key={p.id} className={nodeClass} style={style} data-point-id={p.id} onClick={()=>onToggle(p.id)} disabled={phase!=="play"} aria-label={"ดาวตำแหน่ง "+(i+1)+(active?" ถูกเลือก":"")} aria-pressed={active}><span className="star-core">✦</span><span className="sensor-ring"/><span className="node-label">{active?"PLAYER":""}</span></button>:<span key={p.id} className={nodeClass} style={style} data-point-id={p.id} aria-hidden="true"><span className="star-core">✦</span><span className="sensor-ring"/><span className="node-label">{active?"PLAYER":""}</span></span>})}</div>
 </div>
}

export default function Home(){
 const [siteView,setSiteView]=useState<SiteView>("game");
 const [phase,setPhase]=useState<Phase>("idle"),[rounds,setRounds]=useState<Constellation[]>([]),[roundIndex,setRoundIndex]=useState(0),[timeLeft,setTimeLeft]=useState(40),[countdown,setCountdown]=useState(3),[questionSeconds,setQuestionSeconds]=useState(5),[questionLeaving,setQuestionLeaving]=useState(false),[selected,setSelected]=useState<Set<string>>(new Set()),[penalized,setPenalized]=useState<Set<string>>(new Set()),[results,setResults]=useState<RoundResult[]>([]),[fastMode,setFastMode]=useState(false),[simplified,setSimplified]=useState(true),[resetIn,setResetIn]=useState(12),[roundDecoys,setRoundDecoys]=useState<Point[]>([]),[attractIndex,setAttractIndex]=useState(4),[attractSeconds,setAttractSeconds]=useState(15),[attractFade,setAttractFade]=useState<""|"out"|"in">("");
 const catalog=simplified?ZODIAC_SIMPLIFIED:ZODIAC;
 const timerRef=useRef<ReturnType<typeof setInterval>|null>(null),current=rounds[roundIndex]??catalog[2],attractCurrent=ZODIAC[attractIndex];
 const total=results.reduce((s,r)=>s+r.score,0),maxTotal=results.reduce((s,r)=>s+r.max,0),sessionMax=rounds.reduce((s,r)=>s+r.points.length,0);
 const nodes=useMemo(()=>[...current.points,...roundDecoys],[current,roundDecoys]);
 const targetIds=useMemo(()=>new Set(current.points.map(p=>p.id)),[current]);
 const attractIds=useMemo(()=>new Set(attractCurrent.points.map(p=>p.id)),[attractCurrent]);
 const clearTimer=()=>{if(timerRef.current){clearInterval(timerRef.current);timerRef.current=null}};
 const startHint=useCallback((index:number,target?:Constellation)=>{clearTimer();setRoundIndex(index);const map=target??rounds[index]??catalog[2],decoyCount=9+Math.floor(Math.random()*4);setRoundDecoys(makeDecoys(map,decoyCount));setSelected(new Set());setPenalized(new Set());setPhase("hint");window.setTimeout(()=>{setCountdown(3);setPhase("countdown")},2000)},[rounds,catalog]);
 const showQuestion=useCallback((index:number)=>{clearTimer();setRoundIndex(index);setRoundDecoys([]);setSelected(new Set());setPenalized(new Set());setQuestionSeconds(5);setQuestionLeaving(false);setPhase("question")},[]);
 const startGame=()=>{const picked=shuffle(catalog).slice(0,5);setRounds(picked);setResults([]);setRoundIndex(0);setSelected(new Set());setPenalized(new Set());window.setTimeout(()=>showQuestion(0),0)};
 const evaluate=useCallback(()=>{clearTimer();const correct=current.points.filter(p=>selected.has(p.id)).length,score=Math.max(0,correct-penalized.size);const result={id:current.id,th:current.th,en:current.en,score,max:current.points.length};setResults(prev=>[...prev,result]);setPhase("reveal");window.setTimeout(()=>setPhase("score"),3000);window.setTimeout(()=>roundIndex>=4?setPhase("summary"):showQuestion(roundIndex+1),5000)},[current,selected,penalized,roundIndex,showQuestion]);
 useEffect(()=>{if(phase!=="question")return;setQuestionSeconds(5);setQuestionLeaving(false);const tick=window.setInterval(()=>setQuestionSeconds(v=>Math.max(1,v-1)),1000),leave=window.setTimeout(()=>setQuestionLeaving(true),4300),next=window.setTimeout(()=>startHint(roundIndex,rounds[roundIndex]),5000);return()=>{window.clearInterval(tick);window.clearTimeout(leave);window.clearTimeout(next)}},[phase,roundIndex,rounds,startHint]);
 useEffect(()=>{if(phase!=="countdown")return;const id=window.setInterval(()=>setCountdown(v=>{if(v<=1){window.clearInterval(id);setTimeLeft(fastMode?10:40);setPhase("play");return 0}return v-1}),1000);return()=>window.clearInterval(id)},[phase,fastMode]);
 useEffect(()=>{if(phase!=="play")return;timerRef.current=setInterval(()=>setTimeLeft(v=>{if(v<=1){clearTimer();window.setTimeout(evaluate,0);return 0}return v-1}),1000);return clearTimer},[phase,evaluate]);
 useEffect(()=>{if(phase!=="idle")return;setAttractIndex(Math.floor(Math.random()*ZODIAC.length));setAttractSeconds(15);let swap=0,finish=0;const ticker=window.setInterval(()=>setAttractSeconds(value=>{if(value>1)return value-1;setAttractFade("out");swap=window.setTimeout(()=>{setAttractIndex(previous=>{let next=previous;while(next===previous)next=Math.floor(Math.random()*ZODIAC.length);return next});setAttractFade("in");finish=window.setTimeout(()=>setAttractFade(""),700)},450);return 15}),1000);return()=>{window.clearInterval(ticker);window.clearTimeout(swap);window.clearTimeout(finish);setAttractFade("")}},[phase]);
 useEffect(()=>{if(phase!=="summary")return;setResetIn(12);const tick=window.setInterval(()=>setResetIn(v=>Math.max(0,v-1)),1000),reset=window.setTimeout(()=>{setPhase("idle");setRounds([]);setResults([]);setRoundIndex(0);setSelected(new Set());setPenalized(new Set())},12000);return()=>{window.clearInterval(tick);window.clearTimeout(reset)}},[phase]);
 const toggle=(id:string)=>{if(phase!=="play")return;if(!targetIds.has(id)){setSelected(prev=>new Set(prev).add(id));setPenalized(prev=>new Set(prev).add(id));return}setSelected(prev=>{const n=new Set(prev);if(n.has(id))n.delete(id);else n.add(id);return n})};
 const answer=phase==="hint"||phase==="reveal"||phase==="score";
 const assistLines=phase==="play"&&timeLeft<=10,assistStars=phase==="play"&&timeLeft<=5,correctSelected=current.points.filter(p=>selected.has(p.id)).length,evaluatedRoundScore=results.at(-1)?.score??0,completion=current.points.length?Math.round(correctSelected/current.points.length*100):0;
 const status=phase==="idle"?"ATTRACT MODE · พร้อมเริ่มภารกิจ":phase==="question"?"กลุ่มดาวในรอบนี้":phase==="hint"?"จดจำรูปกลุ่มดาว":phase==="countdown"?"เตรียมเข้าประจำตำแหน่ง":phase==="play"?"เลือกดาวที่ถูกต้อง":phase==="reveal"?"เฉลยคำตอบ":phase==="score"?"คะแนนรอบนี้":"สรุปภารกิจ";
 if(siteView!=="game") return <DesignExplorer view={siteView} onView={setSiteView}/>;
 return <main className="app-shell"><div className="ambient ambient-a"/><div className="ambient ambient-b"/>
  <header className="topbar"><div className="brand"><span className="brand-mark">✦</span><span>CONSTELLATION MAKER</span></div><nav className="site-view-nav" aria-label="ดูเกมและเอกสารออกแบบ"><button className="active" onClick={()=>setSiteView("game")}>เล่นเกม</button><button onClick={()=>setSiteView("mockup")}>UI Mockup</button><button onClick={()=>setSiteView("flow")}>Game Flow</button></nav><div className="mode-controls"><label className="fast-toggle map-toggle"><input type="checkbox" checked={simplified} onChange={e=>setSimplified(e.target.checked)} disabled={phase!=="idle"}/><span/><b>{simplified?"SIMPLIFIED":"REAL"}</b><small>{phase==="idle"?"NEXT GAME":`${current.points.length} PTS`}</small></label><label className="fast-toggle"><input type="checkbox" checked={fastMode} onChange={e=>setFastMode(e.target.checked)} disabled={phase!=="idle"&&phase!=="summary"}/><span/>โหมดทดสอบ 10 วิ</label></div></header>
  <section className={`wall-screen phase-${phase}${phase==="idle"&&attractFade?` attract-fade-${attractFade}`:""}${phase==="question"&&questionLeaving?" question-leaving":""}`} aria-label="จอโค้งบนกำแพงสำหรับแสดงข้อมูล"><div className="screen-grid"/><div className="round-pill">{phase==="idle"?`NEXT CONSTELLATION · ${String(attractSeconds).padStart(2,"0")} SEC`:`ROUND ${Math.min(roundIndex+1,5)} / 5`}</div><div className="wall-center"><div className="zodiac-symbol">{phase==="idle"?attractCurrent.symbol:current.symbol}</div><div><p className="eyebrow">{status}</p><h1>{phase==="idle"?"ปลุกกลุ่มดาวให้สว่างไปด้วยกัน":current.th}</h1><p className="english-name">{phase==="idle"?"STEP ON A STAR · BUILD THE CONSTELLATION":current.en}</p></div></div>
  {phase==="idle"&&<ConstellationMap key={`wall-${attractCurrent.id}`} mode="wall" current={attractCurrent} nodes={attractCurrent.points} targetIds={attractIds} selected={attractIds} phase="idle" answer={false} assistLines={false} assistStars={false} onToggle={()=>{}}/>}
  {phase==="question"&&<ConstellationMap mode="wall" current={current} nodes={current.points} targetIds={targetIds} selected={targetIds} phase="question" answer={false} assistLines={false} assistStars={false} onToggle={()=>{}}/>}
  {phase!=="idle"&&phase!=="question"&&phase!=="summary"&&<ConstellationMap mode="wall" current={current} nodes={nodes} targetIds={targetIds} selected={selected} phase={phase} answer={answer} assistLines={assistLines} assistStars={assistStars} onToggle={toggle}/>}
  {phase==="question"&&<div className="question-overlay"><small>ROUND {roundIndex+1} / 5 · NEW CONSTELLATION</small><span className="question-symbol">{current.symbol}</span><p>โจทย์รอบนี้</p><h2>{current.th}</h2><b>{current.en}</b><div className="player-requirement"><strong>{current.points.length}</strong><span>ผู้เล่นที่ต้องการ<small>1 คนต่อดาวเป้าหมาย</small></span></div><div className="question-progress"><i/></div></div>}
  <div className={`timer ${timeLeft<=10&&phase==="play"?"urgent":""}`}><span>{phase==="play"?String(timeLeft).padStart(2,"0"):phase==="question"?String(questionSeconds).padStart(2,"0"):phase==="idle"?"∞":"—"}</span><small>{phase==="play"?"SECONDS":phase==="question"?"INTRO":phase==="idle"?"WAITING":"TIMER"}</small></div>{phase==="countdown"&&<div className="countdown-overlay wall-countdown"><small>GET READY</small><strong key={countdown}>{countdown}</strong></div>}<div className="score-chip">{phase==="idle"?<><small>CONSTELLATION</small><strong>{attractCurrent.en}</strong><span>/ {attractCurrent.points.length} STARS</span></>:<><small>SCORE</small><strong>{phase==="play"?total+correctSelected:total}</strong><span>/{sessionMax||"—"}</span></>}</div>
  {phase==="idle"&&<div className="wall-cta"><p><b>{attractCurrent.symbol} {attractCurrent.en}</b><span>{attractCurrent.th} · เปลี่ยนรูปใหม่ใน {attractSeconds} วินาที</span></p><button onClick={startGame}><i/>ยืนบนดาวหรือกดเพื่อเริ่มภารกิจ <span>→</span></button></div>}
  {phase==="score"&&<div className="result-pop"><small>ROUND SCORE</small><strong>{results.at(-1)?.score}/{results.at(-1)?.max}</strong><span>{results.at(-1)?.score===results.at(-1)?.max?"PERFECT CONSTELLATION!":"เกือบสำเร็จ ลองจดจำรูปต่อไป"}</span></div>}
  {phase==="summary"&&<div className="summary-overlay"><p className="eyebrow">MISSION COMPLETE</p><h2>{total}/{maxTotal} คะแนน</h2><div className="rank">ความแม่นยำ {maxTotal?Math.round(total/maxTotal*100):0}%</div><div className="round-results">{results.map((r,i)=><div key={r.id}><span>{i+1}</span><p>{r.th}<small>{r.en}</small></p><strong>{r.score}/{r.max}</strong></div>)}</div><div className="auto-reset">กลับหน้าหลักอัตโนมัติใน {resetIn} วินาที</div></div>}</section>
  <div className="display-divider"><span>WALL DISPLAY</span><i/><span>INTERACTIVE FLOOR</span></div>
  <section className={`floor-zone phase-${phase}${phase==="idle"&&attractFade?` attract-fade-${attractFade}`:""}${phase==="question"&&questionLeaving?" question-leaving":""}`} aria-label="จอพื้นที่โต้ตอบได้"><div className="floor-arc"><div className="floor-grid"/></div><div className="floor-instruction"><span className="live-dot"/>{phase==="play"?"คลิกหรือแตะดาวเพื่อจำลองผู้เล่นยืนบนตำแหน่ง · ดาวหลอกจะหัก 1 แต้มเมื่อจบรอบ":phase==="question"?`เตรียมผู้เล่น ${current.points.length} คน · 1 คนต่อดาวเป้าหมาย`:phase==="hint"?"คำใบ้จะแสดง 2 วินาที":phase==="countdown"?"เตรียมเข้าประจำตำแหน่ง":phase==="reveal"||phase==="score"?"สีเขียว = ถูก · สีแดง = ดาวหลอก · วงแหวน = จุดที่พลาด":phase==="idle"?`${attractCurrent.th}กำลังรอคุณ · เปลี่ยนรูปใหม่ใน ${attractSeconds} วินาที`:"จอพื้นจำลอง · จำนวนผู้เล่นยืดหยุ่นตามจำนวนจุดจริง"}</div>{phase==="countdown"&&<div className="countdown-overlay floor-countdown"><small>เตรียมตัว</small><strong key={`floor-${countdown}`}>{countdown}</strong></div>}
  {phase==="play"&&<div className="completion-chip">COMPLETION <strong>{completion}%</strong><small>{correctSelected}/{current.points.length} TARGETS</small></div>}{(phase==="reveal"||phase==="score")&&penalized.size>0&&<div className="penalty-chip">−{penalized.size} <small>ดาวหลอก</small></div>}<ConstellationMap key={phase==="idle"?`floor-${attractCurrent.id}`:phase==="question"?`floor-question-${current.id}`:"floor-game"} mode="floor" current={phase==="idle"?attractCurrent:current} nodes={phase==="idle"?attractCurrent.points:phase==="question"?current.points:nodes} targetIds={phase==="idle"?attractIds:targetIds} selected={phase==="idle"?attractIds:phase==="question"?targetIds:selected} phase={phase} answer={answer} assistLines={assistLines} assistStars={assistStars} onToggle={toggle}/>
  <div className="floor-legend"><span><i className="legend-star"/> ดาวที่เลือก</span><span><i className="legend-line"/> เส้นเชื่อมที่ค้นพบ</span><span><kbd>CLICK</kbd> จำลองการเหยียบ</span></div></section>
  <footer className="control-dock"><div><span className="control-label">GAME STATE</span><strong>{phase==="idle"?"ATTRACT":phase.toUpperCase()}</strong></div><div><span className="control-label">{phase==="idle"?"PREVIEW STARS":"ROUND SCORE"}</span><strong>{phase==="idle"?attractCurrent.points.length:phase==="play"?correctSelected:(phase==="reveal"||phase==="score")?evaluatedRoundScore:0}<small>{phase==="idle"?`/ ${attractCurrent.points.length}`:(phase==="reveal"||phase==="score")?` · −${penalized.size} PENALTY`:" · PENDING"}</small></strong></div><div className="progress-block"><span className="control-label">ROUND PROGRESS</span><div className="progress-dots">{[0,1,2,3,4].map(i=><i key={i} className={i<results.length?"done":i===roundIndex&&phase!=="idle"?"current":""}/>)}</div></div>{phase==="play"&&<button className="submit-button" onClick={evaluate}>SUBMIT คำตอบ <span>✓</span></button>}{phase!=="idle"&&phase!=="summary"&&<button className="reset-button" onClick={()=>{clearTimer();setPhase("idle");setResults([]);setSelected(new Set());setPenalized(new Set())}}>ยกเลิกเกม</button>}</footer>
 </main>
}
